---
ignored:
  - DL3007  # Using latest is prone to errors if the image will ever update. Pin the version explicitly to a release tag
  - DL3013  # Pin versions in pip install.
  - DL3041  # Specify version with `dnf install -y <package>-<version>`.

trustedRegistries:
  - "docker.io"
  - "*.ghcr.io"
  - "quay.io"
